/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_android_serial_api_serial_port */
#ifndef _Included_io_android_serial_api_serial_port
#define _Included_io_android_serial_api_serial_port
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_android_serial_api_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_io_android_serial_api_SerialPort_open(JNIEnv *, jclass, jstring, jint, jint);
/*
 * Class:     io_android_serial_api_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_android_serial_api_SerialPort_close(JNIEnv *, jobject);
#ifdef __cplusplus
}
#endif
#endif

